(deftheme codersean
  "Created 2012-10-10.")

(custom-theme-set-variables
 'codersean
 '(ansi-color-names-vector ["#1A1A1A" "#fdc254" "#95e454" "#cae682" "#b36427" "#333366" "#ccaa8f" "#f6f3e8"]))

(custom-theme-set-faces
 'codersean
 '(cursor ((((class color) (min-colors 89)) (:background "#FFFFFF"))))
 '(fringe ((((class color) (min-colors 89)) (:background "#242424" :foreground "#464646"))))
 '(linum ((((class color) (min-colors 89)) (:background "#242424" :foreground "#464646"))))
 '(highlight ((((class color) (min-colors 89)) (:background "#454545" :foreground "#ffffff" :underline t))))
 '(region ((((class color) (min-colors 89)) (:background "#444444" :foreground "#f6f3e8"))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#333366" :foreground "#f6f3e8"))))
 '(isearch ((((class color) (min-colors 89)) (:background "#343434" :foreground "#857b6f"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:background "#384048" :foreground "#a0a8b0"))))
 '(mode-line ((((class color) (min-colors 89)) (:background "#444444" :foreground "#f6f3e8" :box nil))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:background "#444444" :foreground "#857b6f" :box nil))))
 '(mode-line-buffer-identification ((((class color) (min-colors 89)) (:background "#444444" :foreground "#00FF00" :underline nil :overline nil))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#fdc254" :background "#1A1A1A" :box nil))))
 '(escape-glyph ((((class color) (min-colors 89)) (:foreground "#ddaa6f" :weight bold))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#fdc254" :weight normal))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#ad2ca3" :weight normal :slant normal))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "#ad2ca3" :weight normal :slant normal))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "#ad2ca3" :weight normal :slant normal))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#fdc254"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#fdc254" :weight normal))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "#b36427" :weight normal))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#87FF08"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#b23939" :weight normal))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#f6f3e8" :weight normal))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:foreground "#ccaa8f"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "#fdc254" :weight normal :slant normal))))
 '(link ((((class color) (min-colors 89)) (:foreground "#b36427" :underline t))))
 '(link-visited ((((class color) (min-colors 89)) (:foreground "#e5786d" :underline t))))
 '(button ((((class color) (min-colors 89)) (:background "#333333" :foreground "#f6f3e8"))))
 '(header-line ((((class color) (min-colors 89)) (:background "#242424" :foreground "#e7f6da"))))
 '(gnus-group-news-1 ((((class color) (min-colors 89)) (:weight bold :foreground "#95e454"))))
 '(gnus-group-news-1-low ((((class color) (min-colors 89)) (:foreground "#95e454"))))
 '(gnus-group-news-2 ((((class color) (min-colors 89)) (:weight bold :foreground "#cae682"))))
 '(gnus-group-news-2-low ((((class color) (min-colors 89)) (:foreground "#cae682"))))
 '(gnus-group-news-3 ((((class color) (min-colors 89)) (:weight bold :foreground "#ccaa8f"))))
 '(gnus-group-news-3-low ((((class color) (min-colors 89)) (:foreground "#ccaa8f"))))
 '(gnus-group-news-4 ((((class color) (min-colors 89)) (:weight bold :foreground "#99968b"))))
 '(gnus-group-news-4-low ((((class color) (min-colors 89)) (:foreground "#99968b"))))
 '(gnus-group-news-5 ((((class color) (min-colors 89)) (:weight bold :foreground "#cae682"))))
 '(gnus-group-news-5-low ((((class color) (min-colors 89)) (:foreground "#cae682"))))
 '(gnus-group-news-low ((((class color) (min-colors 89)) (:foreground "#99968b"))))
 '(gnus-group-mail-1 ((((class color) (min-colors 89)) (:weight bold :foreground "#95e454"))))
 '(gnus-group-mail-1-low ((((class color) (min-colors 89)) (:foreground "#95e454"))))
 '(gnus-group-mail-2 ((((class color) (min-colors 89)) (:weight bold :foreground "#cae682"))))
 '(gnus-group-mail-2-low ((((class color) (min-colors 89)) (:foreground "#cae682"))))
 '(gnus-group-mail-3 ((((class color) (min-colors 89)) (:weight bold :foreground "#ccaa8f"))))
 '(gnus-group-mail-3-low ((((class color) (min-colors 89)) (:foreground "#ccaa8f"))))
 '(gnus-group-mail-low ((((class color) (min-colors 89)) (:foreground "#99968b"))))
 '(gnus-header-content ((((class color) (min-colors 89)) (:foreground "#b36427"))))
 '(gnus-header-from ((((class color) (min-colors 89)) (:weight bold :foreground "#95e454"))))
 '(gnus-header-subject ((((class color) (min-colors 89)) (:foreground "#cae682"))))
 '(gnus-header-name ((((class color) (min-colors 89)) (:foreground "#b36427"))))
 '(gnus-header-newsgroups ((((class color) (min-colors 89)) (:foreground "#cae682"))))
 '(message-header-name ((((class color) (min-colors 89)) (:foreground "#b36427" :weight bold))))
 '(message-header-cc ((((class color) (min-colors 89)) (:foreground "#95e454"))))
 '(message-header-other ((((class color) (min-colors 89)) (:foreground "#95e454"))))
 '(message-header-subject ((((class color) (min-colors 89)) (:foreground "#cae682"))))
 '(message-header-to ((((class color) (min-colors 89)) (:foreground "#cae682"))))
 '(message-cited-text ((((class color) (min-colors 89)) (:foreground "#99968b"))))
 '(message-separator ((((class color) (min-colors 89)) (:foreground "#fdc254" :weight bold))))
 '(default ((t (:background "#1A1A1A" :foreground "#f6f3e8")))))

(provide-theme 'codersean)
